@url_dev=http://localhost:8080

### create admin

POST {{url_dev}}/api/user/create-admin
Content-Type: application/json

{
  "msv": "a41954",
  "password": "a41954"
  
}


### Create user
POST {{url_dev}}/api/user/create-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTE1NjA4MzEyYmViY2M2YjlkY2Y3MCIsImlzQWRtaW4iOnRydWUsImlzR1YiOmZhbHNlLCJpYXQiOjE3MjEyMTM0MTQsImV4cCI6MTcyMTI5OTgxNH0.uLsQ2A10PeQv3sQy2mSzYDoEwOeCUG4lOThuAwDE1ss

{
  "fullname": "Nguyen Vu Tien",
  "msv": "A32971",
  "year": 2024,
  "gvcn": "GV123",
  "gender": "Male",
  "className": "CS2024",
  "email": "nguyenvtien@example.com",
  "majorId": "6696101482c5d59352695252"
}



### Get user

// eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGE3NGU2ZWMxMmE3YjAwZDc3ZmNlMSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcyMDM0OTk1NCwiZXhwIjoxNzUxODg1OTU0fQ.mlNbbS20rsMbAZg0cUCvF921TPD1QHxyd6rlZvpFqgg

GET {{url_dev}}/api/user/getAll
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTE1NjA4MzEyYmViY2M2YjlkY2Y3MCIsImlzQWRtaW4iOnRydWUsImlzR1YiOmZhbHNlLCJpYXQiOjE3MjA4NTg4MTEsImV4cCI6MTcyMDg1ODg1MX0.Dd-onEn2lqoWh2jcCb2yC4tHyIIuuDvv6TtZBeFhoxU

### get user id
GET {{url_dev}}/api/user/668d13af9789c62f51b7b385
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGE3NGU2ZWMxMmE3YjAwZDc3ZmNlMSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcyMDUzNzIzMiwiZXhwIjoxNzIwNzk2NDMyfQ.c85W0AosmFCnkMzrBL98-sLKraAFJQSqF2r5Ql7BgEU


### search Student

POST {{url_dev}}/api/user/searchStudents?keyword=A3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTE1NjA4MzEyYmViY2M2YjlkY2Y3MCIsImlzQWRtaW4iOnRydWUsImlzR1YiOmZhbHNlLCJpYXQiOjE3MjEyMTM0MTQsImV4cCI6MTcyMTI5OTgxNH0.uLsQ2A10PeQv3sQy2mSzYDoEwOeCUG4lOThuAwDE1ss
