@url_dev=http://localhost:8080

### create admin

POST {{url_dev}}/api/user/create-admin
Content-Type: application/json

{
  "msv": "a41954",
  "password": "a41954"
  
}


### Create user
POST {{url_dev}}/api/user/create-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGE3NGU2ZWMxMmE3YjAwZDc3ZmNlMSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcyMDUxOTUzMCwiZXhwIjoxNzIwNTI2NzMwfQ.6ZfXDz-R2ExCl1lvSfsG3d6ieEuTudMDM9bTCdob8oQ


{
  "fullname": "Nguyen Van A",
  "msv": "A41954",
  "major": "Computer Science",
  "year": 2024,
  "gvcn": "GV123",
  "gender": "Male",
  "className": "CS2024",
  "email": "nguyenvana@example.com"
}



### Get user

// eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGE3NGU2ZWMxMmE3YjAwZDc3ZmNlMSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcyMDM0OTk1NCwiZXhwIjoxNzUxODg1OTU0fQ.mlNbbS20rsMbAZg0cUCvF921TPD1QHxyd6rlZvpFqgg

GET {{url_dev}}/api/user/getAll
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGE3NGU2ZWMxMmE3YjAwZDc3ZmNlMSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcyMDQyNTY2OCwiZXhwIjoxNzIwNDMyODY4fQ.G0AvOpMwHsuorwpwKaKlnzZJ6Nh0SjqAHy2rLZspt4c
# "tokens": {
#     "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGE3NGU2ZWMxMmE3YjAwZDc3ZmNlMSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcyMDM1MDY2MywiZXhwIjoxNzIwMzU3ODYzfQ.upIMojlGwhXBqxd0-u18yU2yOeRajVqJsM46G6zn3YM",
#     "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGE3NGU2ZWMxMmE3YjAwZDc3ZmNlMSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcyMDM1MDY2MywiZXhwIjoxNzUxODg2NjYzfQ.L3IR7_hNBezUF0eskI7NmI1KVu6YICmMxbmquPzWEss"
#   }



### get user id
GET {{url_dev}}/api/user/668a74e6ec12a7b00d77fce1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGE3NGU2ZWMxMmE3YjAwZDc3ZmNlMSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcyMDUxOTUzMCwiZXhwIjoxNzIwNTI2NzMwfQ.6ZfXDz-R2ExCl1lvSfsG3d6ieEuTudMDM9bTCdob8oQ
